# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Timeline' do
pod 'pop', '~> 1.0'

end

target 'TimelineTests' do

end

target 'TimelineUITests' do

end

